<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;"> <!--<![endif]-->
    <head>
        <!-- Basic Page Needs -->
        <meta charset="utf-8"  >
        <title>LocName</title>
    </head>
    <body style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;background-color: #f1f1f3;color: #848994;font-family: 'Open Sans',Arial;font-size: 13px;line-height: 22px;-webkit-font-smoothing: antialiased;">
        <div class="container clearfix" style="margin: auto;padding: 20px;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;background-color: #FFF;border-left: 1px solid #d6d9df;border-right: 1px solid #d6d9df;width: 604px;">
            <div class="header-top" style="margin: 0;padding: 0 10px;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;border: 1px solid #e7e8eb;background-color: #f5f6f8;line-height: 45px;margin-bottom: 10px; vertical-align:middle;">
                <div class="phone-mail" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;font-size: 12px;float: left;">Welcome To LocName.com</div>
                <div class="social" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box; float: right;">
                    <ul style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;list-style: none;">
                        <li class="social-g" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;float: right;margin-left: 5px;"><a href="https://google.com/+LocName" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #FFF;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in;display: inline-block;font-size: 12.5px;line-height: 25px;height: 25px;width: 25px;text-align: center;-moz-border-radius: 2px;-webkit-border-radius: 2px;border-radius: 2px;"><i class="fa fa-google-plus" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box; display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale"><img src="<?= base_url("assets/images/icons")?>/g+1.png" alt="" style=" vertical-align:middle;"></i></a></li>
                        <li class="social-t" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;float: right;margin-left: 5px;"><a href="https://twitter.com/Loc_Name" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #FFF;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in;display: inline-block;font-size: 12.5px;line-height: 25px;height: 25px;width: 25px;text-align: center;-moz-border-radius: 2px;-webkit-border-radius: 2px;border-radius: 2px;"><i class="fa fa-twitter" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box; display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale"><img src="<?= base_url("assets/images/icons")?>/twitter1.png" alt="" style=" vertical-align:middle;"></i></a></li>
                        <li class="social-f" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;float: right;margin-left: 5px;"><a href="http://facebook.com/Locname" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #FFF;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in;display: inline-block;font-size: 12.5px;line-height: 25px;height: 25px;width: 25px;text-align: center;-moz-border-radius: 2px;-webkit-border-radius: 2px;border-radius: 2px;"><i class="fa fa-facebook" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box; display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale"><img src="<?= base_url("assets/images/icons")?>/fb1.png" alt="" style=" vertical-align:middle;"></i></a></li>
                    </ul>
                </div>
                <div class="clearfix" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;"></div>
            </div>
            <center><a class="logo" href="<?= site_url() ?>" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #3498db;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in;"><img alt="" src="<?= base_url("assets/images")?>/email_logo.png"></a></center>
            <div class="clearfix" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;"></div>
            <div class="congratulations" style="margin: 70px 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;text-align: center;">
            <h3 style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;line-height: 1.4em;color: #3498db;font-size: 30px;font-weight: bold;margin-bottom: 20px;">Password Reset</h3>
                <div style="text-align: left;margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;">

                    <p style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;">Hey <?php echo $identity; ?>, </p>
                    <p style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;">  </p><br/> 
                    You asked us to reset your forgotten password. To complete the process, please click on the link below or paste it into your browser:<br/>
                    <br/>
<p style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;"><?php echo anchor('auth/reset_password' . "/" . $forgotten_password_code, site_url('auth/reset_password/') . $forgotten_password_code); ?></p>
                </div>
            </div>
            <div class="clearfix" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;"></div>
            <div class="social-2" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;text-align: center;">
                <ul style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;">
                    <li class="social-f" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;display: inline-block;margin-right: 20px;margin-bottom: 40px;">
                    	<a href="http://facebook.com/Locname" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #3498db;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in;"><i class="fa fa-facebook" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;"><img src="<?= base_url("assets/images/icons")?>/fb2.png" alt=""></i></a>
                    </li>
                    <li class="social-t" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;display: inline-block;margin-right: 20px;margin-bottom: 40px;">
						<a href="https://twitter.com/Loc_Name" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #3498db;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in;"><i class="fa fa-twitter" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;"><img src="<?= base_url("assets/images/icons")?>/twitter2.png" alt=""></i></a>
                    </li>
                    <li class="social-g" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;display: inline-block;margin-right: 20px;margin-bottom: 40px;">
						<a href="https://google.com/+LocName" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #3498db;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in;"><i class="fa fa-google-plus" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;"><img src="<?= base_url("assets/images/icons")?>/g+2.png" alt=""></i></a>
                    </li>
                </ul>
            </div>
            <div class="clearfix" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;"></div>
            <div class="footer" style="margin: 0;padding: 20px;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;background-color: #e1f0fa;border: 1px solid #aed6f1;margin-bottom: 10px;">
                <h3 style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;line-height: 1.4em;color: #2c3e50;font-size: 15px;font-weight: bold;margin-bottom: 20px;">Contact Us</h3>
                <ul style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;list-style: none;">
                    <li style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;margin-bottom: 10px;">
                        <div style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;overflow: hidden;height: 100%;"><strong style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #3498db;"><i class="fa fa-map-marker" style="display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale"><img src="<?= base_url("assets/images/icons")?>/map.png" alt="" style=" vertical-align:middle;"></i> Address:</strong> The GrEEK Campus, 28 Falaki St., Bab Ellouk, Downtown, Cairo, Egypt

                        </div>
                    </li>

                    <li style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;margin-bottom: 10px;">
                    	<div style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;overflow: hidden;height: 100%;"><strong style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #3498db;"><i class="fa fa-envelope" style="display:inline-block;font-family:FontAwesome;font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale"><img src="<?= base_url("assets/images/icons")?>/mail.png" alt="" style="vertical-align:middle;"></i> Email:</strong>  
                            <span style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #2c3e50;">info@locname.com</div>
                    </li>
                </ul>
            </div>
            <div class="clearfix" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;"></div>
            <div class="header-top footer-bottom" style="margin: 0;padding: 0 10px;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;border: 1px solid #e7e8eb;background-color: #f5f6f8;line-height: 45px;margin-bottom: 0;">
                
                <a class="copyright" href="<?= site_url() ?>" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;color: #3498db;text-decoration: none;-webkit-transition: all 150ms ease-in;-moz-transition: all 150ms ease-in;-o-transition: all 150ms ease-in;transition: all 150ms ease-in; float:right;">© LocName.com</a>
                <div class="clearfix" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;"></div>
            </div>
            <div class="clearfix" style="margin: 0;padding: 0;outline: none;-moz-box-sizing: border-box;-webkit-box-sizing: border-box;box-sizing: border-box;clear: both;"></div>
        </div>
    </body>
</html>